CXX = g++
CXXFLAGS = -std=c++17 -O2 -Wall -Wextra -Iinclude


SRC = $(wildcard src/*.cpp)
OBJ = $(SRC:.cpp=.o)
TARGET = snakegame


all: $(TARGET)


$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^


src/%.o: src/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@


clean:
	rm -f $(OBJ) $(TARGET)

